env:
    - TRAVIS_TEST=1

before_install:
    - echo before_install

install: echo install

before_script:
    - echo before_script

script:
    - if [ ! $TRAVIS_TEST ]; then exit 1; fi
    - echo script
