#!/bin/bash

main()
{
    if [ $# -gt 0 ]
    then
        local actions=($1)
        shift
    else
        local actions=( \
            "services" \
            "env" \
            "before_install" \
            "install" \
            "before_script" \
            "script" \
            "after_success" \
            "before_deploy" \
            "deploy" \
            "after_deploy" \
            "after_script" \
        )
    fi

    for action in "${actions[@]}"
    do
        execute "$action"
        local status=$?

        if [ $status -ne 0 ]
        then
            execute "after_failure"
            return $status
        fi
    done
}

execute()
{
    local commands=$(get "$1")
    local command

    if [ $? != 0 ]
    then
        return 0
    fi

    IFS=$'\n'
    for command in $commands
    do
        case "$1" in
            "services")
                command="sudo service $command start"
            ;;
            "env")
                command="export $command"
            ;;
        esac

        execute_command "$command"
        local status=$?

        if [ $status -ne 0 ]
        then
            return $status
        fi
    done
}

execute_command()
{
    local command="$1"

    eval $command
    local status=$?

    if [ $status -eq 0 ]
    then
        echo -en "\e[32m\e[1m✓\e[0m"
    else
        echo -en "\e[31m\e[1mx\e[0m"
    fi

    echo " $command"

    if [ $status -ne 0 ]
    then
        return $status
    else
        echo ""
    fi
}

get()
{
    local key=$1

    echo "$TRAVIS" | shyaml get-values $key 2> /dev/null
    if [ $? != 0 ]
    then
        echo "$TRAVIS" | shyaml get-value $key 2> /dev/null
    fi
}

die()
{
    echo $@
    exit 1
}

test -e .travis.yml || die 'No .travis.yml script'

readonly TRAVIS=$(cat .travis.yml)

main $@
