#!/bin/bash

set -e

die()
{
    echo $@
    exit 1
}

get()
{
    local key=$1

    echo "$TRAVIS" | shyaml get-values $key 2> /dev/null
    if [ $? != 0 ]
    then
        echo "$TRAVIS" | shyaml get-value $key 2> /dev/null
    fi
}

execute_command()
{
    local command="$1"

    eval $command
    local status=$?

    if [ $status == 0 ]
    then
        echo -en "\e[32m\e[1m✓\e[0m"
    else
        echo -en "\e[31m\e[1mx\e[0m"
    fi

    echo " $command"

    if [ $status != 0 ]
    then
        return $status
    else
        echo ""
    fi
}

execute()
{
    local commands=$(get "$1")
    local command

    if [ $? != 0 ]
    then
        return 0
    fi

    IFS=$'\n'
    for command in $commands
    do
        case "$1" in
            "services")
                command="sudo service $command start"
            ;;
            "env" )
                command="export $command"
            ;;
        esac

        execute_command "$command"

        if [ $? != 0 ]
        then
            return $status
        fi
    done
}

test -e .travis.yml || die 'No .travis.yml script'

readonly TRAVIS=$(cat .travis.yml)

execute "services" \
    && execute "env" \
    && execute "before_install" \
    && execute "install" \
    && execute "before_script" \
    && execute "script" \
    && execute "after_success" \
    && execute "before_deploy" \
    && execute "deploy" \
    && execute "after_deploy" \
    && execute "after_script" \
    || execute "after_failure"
